# Generated by Django 5.1.5 on 2025-01-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfounditem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
        migrations.AlterField(
            model_name='lostandfounditem',
            name='contact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lostandfounditem',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lostandfounditem',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lostandfounditem',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lostandfounditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_and_found_images/'),
        ),
        migrations.AlterField(
            model_name='lostandfounditem',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lostandfounditem',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lostandfounditem',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10),
        ),
    ]
