# Generated by Django 5.1.5 on 2025-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_lostandfounditem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfounditem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
