# Generated by Django 5.1.5 on 2025-01-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_lostandfounditem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfounditem',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
